"""
Feature Names Configuration for Student Performance Prediction

This module contains the predefined feature names for different questions in the
student performance prediction pipeline. These feature names are generated through
advanced feature engineering using Polars and represent the final feature set
that gets fed into the XGBoost models for each question.

The features are organized by question number and represent the output of a
complex feature engineering process that transforms raw gameplay events into
meaningful numerical representations for machine learning.

Key Concepts:
- I_FEATURES: Question-specific feature sets for questions 3, 12, and 13
- Feature Naming Convention: Features follow the pattern [element]_[metric]_[aggregation]
- Aggregation Types: max_, sum_, mean_, counts for different statistical measures
- Element Types: text, fqid, room_fqid, event_name, coordinates, timing

Feature Engineering Process:
1. Raw gameplay events (clicks, hovers, navigation) are processed
2. Categorical variables are transformed into numerical features
3. Temporal and spatial patterns are extracted
4. Statistical aggregations are computed per session
5. Question-specific features are selected based on importance

Author: Competition Team
Competition: Predict Student Performance from Game Play
Position: 35/2051 (Silver Medal)
"""

I_FEATURES = {
    12: {
        "*COUGH COUGH COUGH*_text_ET_max_",
        "Can you help me tidy up?_text_ET_max_",
        "Check out our microfiche. It's right through that door._text_ET_max_",
        "Check out our microfiche. It's right through that door._text_ET_sum_",
        "Do you have any info on Theodora Youmans?_text_ET_max_",
        "Do you have any info on Theodora Youmans?_text_ET_sum_",
        "Do you know anything about this slip?_text_ET_sum_",
        "Ha! Good one._text_ET_sum_",
        "He was looking for a taxidermist._text_ET_max_",
        "He's always trying to get you in trouble, and he doesn't like animals!_text_ET_max_",
        "Hello there!_text_ET_max_",
        "Hey, this is Youmans!_text_ET_sum_",
        "Hmm. Button's still not working._text_ET_sum_",
        "How can I help you?_text_ET_max_",
        "I don't know!_text_ET_max_",
        "I don't need that right now._text_ET_max_",
        "I got here and the whole place was ransacked!_text_ET_max_",
        "I got that one from my Gramps!_text_ET_max_",
        "I haven't quite figured it out just yet..._text_ET_max_",
        "I knew I could count on you, Jo!_text_ET_sum_",
        "I should go to the Capitol and tell everyone!_text_ET_max_",
        "I'm Leopold's grandkid!_text_ET_max_",
        "I'm Leopold's grandkid!_text_ET_sum_",
        "I'm afraid my papers have gone missing in this mess._text_ET_max_",
        "I'm afraid my papers have gone missing in this mess._text_ET_sum_",
        "I'm sure you'll find Theodora in there somewhere!_text_counts",
        "I've got a stack of business cards from my favorite cleaners._text_ET_sum_",
        "Is this your coffee, Gramps?_text_ET_max_",
        "It's for Grampa Leo. He's a historian!_text_ET_max_",
        "It's for Grampa Leo. He's a historian!_text_ET_sum_",
        "Maybe I can help!_text_ET_max_",
        "Oh, that's from Bean Town._text_ET_max_",
        "Poor Gramps! I should make sure he's okay._text_ET_max_",
        "Right outside the door._text_ET_sum_",
        "Slow down, Jo._text_ET_max_",
        "Sorry, I'm too busy for kids right now._text_ET_sum_",
        "Sorry, can't help you._text_ET_max_",
        "Sorry, can't help you._text_ET_sum_",
        "Take a look!_text_ET_max_",
        "Thanks to them, Wisconsin was the first state to approve votes for women!_text_ET_max_",
        "Thanks to them, Wisconsin was the first state to approve votes for women!_text_ET_sum_",
        "The archivist said I should look in the stacks._text_ET_sum_",
        "Theodora Youmans must be the owner!_text_ET_max_",
        "Theodora Youmans must be the owner!_text_ET_sum_",
        "Theodora Youmans? Is that who owned the shirt?_text_ET_max_",
        "Theodora Youmans? Of course!_text_ET_max_",
        "They study clothes and fabric._text_ET_max_",
        "They study clothes and fabric._text_ET_sum_",
        "This button never works!_text_ET_max_",
        "Two missions, actually!_text_ET_sum_",
        "Wait a sec. Women couldn't vote?!_text_ET_max_",
        "Wells! What was he doing here? I should ask the librarian._text_ET_sum_",
        "Wells? I knew it!_text_ET_max_",
        "Wells? I knew it!_text_ET_sum_",
        "What happened here?!_text_ET_sum_",
        "What's a taxidermist?_text_ET_sum_",
        "Where are the Stacks?_text_ET_max_",
        "Where should I go again?_text_ET_sum_",
        "Who could've done this?_text_ET_max_",
        "Who could've done this?_text_ET_sum_",
        "Why don't you take a look?_text_ET_max_",
        "Wow!_text_ET_max_",
        "Yeah. Thanks anyway._text_ET_sum_",
        "Yep._text_ET_max_",
        "Yes! I was wondering-_text_ET_sum_",
        "Yes!_text_ET_sum_",
        "You could ask the archivist. He knows everybody!_text_ET_max_",
        "You could ask the archivist. He knows everybody!_text_ET_sum_",
        "You'll have to get started without me._text_ET_sum_",
        "You're still here? I'm trying to work!_text_counts",
        "Youmans was a suffragist here in Wisconsin._text_ET_max_",
        "Youmans was a suffragist!_text_ET_max_",
        "Your gramps is awesome! Always full of stories._text_ET_max_",
        "\\Taxidermy: the art of preparing, stuffing, and mounting the skins of animals.\\_text_ET_max_",
        "\\Taxidermy: the art of preparing, stuffing, and mounting the skins of animals.\\_text_ET_sum_",
        "block_ET_max_",
        "boss_ET_max_",
        "businesscards.card_0.next_ET_sum_",
        "businesscards.card_1.next_ET_max_",
        "businesscards.card_1.next_ET_mean_",
        "businesscards.card_bingo.next_ET_max_",
        "businesscards.card_bingo.next_ET_mean_",
        "businesscards.card_bingo.next_ET_sum_",
        "businesscards_ET_max_",
        "businesscards_ET_sum_",
        "checkpoint_ET_max_",
        "close_ET_max_",
        "cutscene_click_ET_max_",
        "directory_ET_max_",
        "door_block_talk_ET_max_",
        "door_block_talk_ET_mean_",
        "door_block_talk_ET_sum_",
        "gramps_ET_sum_",
        "gramps_fqid_counts",
        "hover_duration_max_",
        "hover_duration_mean_",
        "journals.hub.topics_ET_max_",
        "journals.hub.topics_ET_mean_",
        "journals.pic_1.next_ET_max_",
        "journals.pic_1.next_fqid_counts",
        "journals.pic_2.bingo_ET_max_",
        "journals.pic_2.bingo_ET_sum_",
        "journals.pic_2.next_ET_max_",
        "journals_ET_sum_",
        "journals_fqid_counts",
        "logbook.page.bingo_ET_max_",
        "logbook.page.bingo_ET_mean_",
        "logbook.page.bingo_ET_sum_",
        "logbook_ET_sum_",
        "logbook_fqid_counts",
        "map_click_ET_mean_x",
        "map_click_event_name_counts",
        "map_hover_ET_mean_",
        "map_hover_event_name_counts",
        "navigate_click_ET_max_x",
        "navigate_click_ET_mean_x",
        "notebook_click_ET_max_",
        "notebook_click_ET_max_x",
        "notification_click_ET_max_",
        "notification_click_ET_mean_",
        "object_click_ET_max_x",
        "object_click_event_name_counts",
        "outtolunch_ET_mean_",
        "page_mean_",
        "reader.paper0.prev_ET_max_",
        "reader.paper0.prev_ET_sum_",
        "reader.paper1.next_ET_max_",
        "reader.paper1.next_ET_mean_",
        "reader.paper1.prev_ET_max_",
        "reader.paper2.bingo_ET_sum_",
        "reader.paper2.next_ET_mean_",
        "reader_ET_sum_",
        "room_coor_x_mean_",
        "session_number_",
        "tobasement_ET_sum_",
        "tobasement_fqid_counts",
        "tocloset_dirty_ET_max_",
        "tocloset_dirty_ET_sum_",
        "toentry_ET_max_",
        "toentry_ET_sum_",
        "tofrontdesk_ET_mean_",
        "tohallway_ET_sum_",
        "tomap_ET_sum_",
        "tostacks_ET_mean_",
        "tostacks_ET_sum_",
        "tostacks_fqid_counts",
        "tunic.capitol_0.hall.boss.talktogramps_ET_mean_",
        "tunic.capitol_0.hall_ET_mean_",
        "tunic.capitol_0_ET_sum_",
        "tunic.capitol_1.hall_ET_sum_",
        "tunic.capitol_1_ET_max_",
        "tunic.capitol_1_ET_sum_",
        "tunic.drycleaner.frontdesk.logbook.page.bingo_ET_mean_",
        "tunic.drycleaner.frontdesk.worker.done_text_fqid_counts",
        "tunic.drycleaner.frontdesk.worker.hub_ET_mean_",
        "tunic.drycleaner.frontdesk_ET_mean_",
        "tunic.drycleaner.frontdesk_room_fqid_counts",
        "tunic.drycleaner_ET_sum_",
        "tunic.historicalsociety.closet_dirty.door_block_talk_ET_mean_",
        "tunic.historicalsociety.closet_dirty.door_block_talk_ET_sum_",
        "tunic.historicalsociety.closet_dirty.gramps.archivist_ET_mean_",
        "tunic.historicalsociety.closet_dirty.gramps.archivist_ET_sum_",
        "tunic.historicalsociety.closet_dirty.gramps.news_ET_max_",
        "tunic.historicalsociety.closet_dirty.gramps.news_ET_mean_",
        "tunic.historicalsociety.closet_dirty.gramps.news_ET_sum_",
        "tunic.historicalsociety.closet_dirty.trigger_scarf_ET_max_",
        "tunic.historicalsociety.collection_ET_max_",
        "tunic.historicalsociety.entry_ET_max_",
        "tunic.historicalsociety.entry_ET_mean_",
        "tunic.historicalsociety.frontdesk.archivist.have_glass_recap_ET_sum_",
        "tunic.historicalsociety.frontdesk.archivist.hello_ET_sum_",
        "tunic.historicalsociety.frontdesk.archivist.newspaper_ET_max_",
        "tunic.historicalsociety.frontdesk_ET_mean_",
        "tunic.historicalsociety.stacks_room_fqid_counts",
        "tunic.historicalsociety_ET_max_",
        "tunic.historicalsociety_ET_mean_",
        "tunic.hub.slip_ET_mean_",
        "tunic.humanecology.frontdesk.worker.badger_ET_max_",
        "tunic.humanecology.frontdesk_room_fqid_counts",
        "tunic.humanecology_ET_max_",
        "tunic.humanecology_ET_mean_",
        "tunic.humanecology_ET_sum_",
        "tunic.kohlcenter.halloffame_ET_mean_",
        "tunic.kohlcenter_ET_mean_",
        "tunic.kohlcenter_fqid_counts",
        "tunic.library.frontdesk.worker.wells_ET_max_",
        "tunic.library.frontdesk.worker.wells_recap_text_fqid_counts",
        "tunic.library.frontdesk_ET_max_",
        "tunic.library.frontdesk_room_fqid_counts",
        "tunic.library.microfiche.reader.paper2.bingo_ET_mean_",
        "tunic.library.microfiche_ET_max_",
        "tunic.library_ET_mean_",
        "wellsbadge_ET_max_",
        "wellsbadge_ET_sum_",
        "worker_ET_sum_",
    },
    13: {
        "Hey, this is Youmans!_text_ET_max_",
        "Hey, this is Youmans!_text_ET_sum_",
        "It's a match!_text_ET_max_",
        "It's a match!_text_ET_sum_",
        "Youmans was a suffragist!_text_ET_sum_",
        "basic_name_counts",
        "hover_duration_max_",
        "journals.hub.topics_ET_max_",
        "journals.hub.topics_ET_sum_",
        "journals.pic_1.next_ET_mean_",
        "journals.pic_1.next_ET_sum_",
        "journals.pic_2.next_ET_sum_",
        "logbook.page.bingo_ET_sum_",
        "notification_click_ET_mean_",
        "object_click_event_name_counts",
        "object_hover_ET_max_",
        "object_hover_ET_mean_",
        "reader.paper0.next_ET_sum_",
        "reader.paper0.prev_ET_mean_",
        "reader.paper1.next_ET_max_",
        "reader.paper1.next_ET_mean_",
        "reader.paper1.next_ET_sum_",
        "room_fqid_unique_",
        "tobasement_ET_max_",
        "tunic.capitol_0.hall_room_fqid_counts",
        "tunic.capitol_1.hall_room_fqid_counts",
        "tunic.drycleaner.frontdesk.logbook.page.bingo_ET_mean_",
        "tunic.historicalsociety.closet_dirty.what_happened_ET_mean_",
        "tunic.historicalsociety.frontdesk.archivist.have_glass_recap_ET_mean_",
        "tunic.historicalsociety.stacks.journals.pic_2.bingo_ET_mean_",
        "tunic.historicalsociety.stacks.journals.pic_2.bingo_ET_sum_",
        "tunic.humanecology.frontdesk.businesscards.card_bingo.bingo_ET_mean_",
        "tunic.library.microfiche.reader.paper2.bingo_ET_sum_",
    },
    3: {
        "A boring old shirt._text_ET_max_",
        "Besides, I already figured out the shirt._text_ET_max_",
        "Besides, I already figured out the shirt._text_ET_sum_",
        "Better check back later._text_ET_sum_",
        "Can I come, Gramps?_text_ET_max_",
        "Can I come, Gramps?_text_ET_sum_",
        "Can I take a closer look?_text_ET_max_",
        "Could be. But we need evidence!_text_ET_sum_",
        "Did you do all of them?_text_ET_max_",
        "Did you do all of them?_text_ET_sum_",
        "Find anything?_text_ET_max_",
        "Find anything?_text_ET_sum_",
        "Found it!_text_ET_max_",
        "Found it!_text_ET_sum_",
        "Go ahead, take a peek at the shirt!_text_ET_max_",
        "Go ahead, take a peek at the shirt!_text_ET_sum_",
        "Grab your notebook and come upstairs!_text_ET_max_",
        "Gramps is a great historian!_text_ET_max_",
        "Gramps is in trouble for losing papers?_text_ET_max_",
        "Gramps is in trouble for losing papers?_text_ET_sum_",
        "Gramps is the best historian ever!_text_ET_max_",
        "Head over to the Basketball Center._text_ET_max_",
        "Head over to the Basketball Center._text_ET_sum_",
        "Hey Jo, let's take a look at the shirt!_text_ET_max_",
        "Hmm. Button's still not working._text_ET_sum_",
        "Hmmm. Don't forget about your homework._text_ET_max_",
        "Hooray, a boring old shirt._text_ET_max_",
        "Hooray, a boring old shirt._text_ET_sum_",
        "Hopefully you can rustle up some clues!_text_ET_max_",
        "Hot Dog! I knew it!_text_ET_max_",
        "Hot Dog! I knew it!_text_ET_sum_",
        "I get to go to Gramps's meeting!_text_ET_max_",
        "I get to go to Gramps's meeting!_text_ET_sum_",
        "I gotta run to my meeting!_text_ET_max_",
        "I gotta run to my meeting!_text_ET_sum_",
        "I knew it!_text_ET_max_",
        "I need to get to the Capitol and tell Gramps!_text_ET_max_",
        "I need to get to the Capitol and tell Gramps!_text_ET_sum_",
        "I suppose historians are boring, too?_text_ET_max_",
        "I suppose historians are boring, too?_text_ET_sum_",
        "I'll be at the Capitol. Let me know if you find anything!_text_ET_max_",
        "I'll be at the Capitol. Let me know if you find anything!_text_ET_sum_",
        "I'll hurry back and then we can go exploring!_text_ET_max_",
        "I'm not so sure that this is a basketball jersey._text_ET_sum_",
        "It's a women's basketball jersey!_text_ET_max_",
        "It's already all done!_text_ET_max_",
        "It's true, they do keep going missing lately._text_ET_max_",
        "It's true, they do keep going missing lately._text_ET_sum_",
        "Just talking to Teddy._text_ET_max_",
        "Just talking to Teddy._text_ET_sum_",
        "Just this old slip from 1916._text_ET_max_",
        "Leopold, why don't you help me set up in the Capitol?_text_ET_max_",
        "Let's get started. The Wisconsin Wonders exhibit opens tomorrow!_text_ET_max_",
        "Let's get started. The Wisconsin Wonders exhibit opens tomorrow!_text_ET_sum_",
        "Look at that! It's the bee's knees!_text_ET_max_",
        "None_text_ET_max_",
        "None_text_ET_sum_",
        "None_text_counts",
        "Now where did I put my notebook?_text_ET_max_",
        "Now where did I put my notebook?_text_ET_sum_",
        "Ooh, I like clues!_text_ET_max_",
        "Ooh, I like clues!_text_ET_sum_",
        "Our shirt is too old to be a basketball jersey!_text_ET_max_",
        "Our shirt is too old to be a basketball jersey!_text_ET_sum_",
        "Plus, my teacher said I could help you out for extra credit!_text_ET_sum_",
        "See you later, Teddy._text_ET_max_",
        "See?_text_ET_sum_",
        "Sure!_text_ET_max_",
        "Teddy and I were gonna go climb that huge tree out back!_text_ET_max_",
        "That settles it._text_ET_max_",
        "That's it!_text_ET_sum_",
        "The slip is from 1916 but the team didn't start until 1974!_text_ET_max_",
        "The slip is from 1916 but the team didn't start until 1974!_text_ET_sum_",
        "Then do it for me!_text_ET_max_",
        "Then do it for me!_text_ET_sum_",
        "This button never works!_text_ET_sum_",
        "This can't be right!_text_ET_max_",
        "This can't be right!_text_ET_sum_",
        "This looks like a clue!_text_ET_max_",
        "This looks like a clue!_text_ET_sum_",
        "Um... what did you want me to do again?_text_ET_max_",
        "Um... what did you want me to do again?_text_ET_sum_",
        "Wait, you mean Wells is wrong?!_text_ET_max_",
        "Wait, you mean Wells is wrong?!_text_ET_sum_",
        "We need to talk about that missing paperwork._text_ET_max_",
        "We need to talk about that missing paperwork._text_ET_sum_",
        "Well, I did SOME of those. I just couldn't find them!_text_ET_sum_",
        "Well, that's good enough for me._text_ET_max_",
        "Wells, finish up your report._text_ET_max_",
        "Wells, finish up your report._text_ET_sum_",
        "What a fascinating artifact!_text_ET_max_",
        "What a fascinating artifact!_text_ET_sum_",
        "Whatcha doing over there, Jo?_text_ET_max_",
        "Whatcha doing over there, Jo?_text_ET_sum_",
        "Who wants to investigate the shirt artifact?_text_ET_max_",
        "Who wants to investigate the shirt artifact?_text_ET_sum_",
        "Why don't you head to the Basketball Center and rustle up some clues?_text_ET_max_",
        "Why don't you head to the Basketball Center and rustle up some clues?_text_ET_sum_",
        "Will do, Boss._text_ET_max_",
        "Will do, Boss._text_ET_sum_",
        "Wow, that's so cool, Gramps!_text_ET_max_",
        "Wow, that's so cool, Gramps!_text_ET_sum_",
        "Yes! This old slip from 1916._text_ET_sum_",
        "Your grampa is waiting for you in the collection room._text_ET_max_",
        "Your teacher said you could help me for extra credit._text_ET_max_",
        "Your teacher said you could help me for extra credit._text_ET_sum_",
        "Your teacher said you missed 7 assignments in a row!_text_ET_max_",
        "\\u00f0\\u0178\\u02dc\\u00b4_text_ET_sum_",
        "basic_ET_max_",
        "basic_ET_mean_",
        "basic_name_counts",
        "chap1_finale_ET_mean_",
        "chap1_finale_ET_sum_",
        "chap1_finale_c_ET_max_",
        "chap1_finale_c_ET_mean_",
        "chap1_finale_c_ET_sum_",
        "chap1_finale_fqid_counts",
        "checkpoint_ET_mean_",
        "close_ET_mean_",
        "cs_ET_max_",
        "cs_ET_sum_",
        "cs_fqid_counts",
        "cutscene_click_ET_max_",
        "cutscene_click_ET_max_x",
        "cutscene_click_ET_mean_x",
        "cutscene_click_event_name_counts",
        "directory_ET_max_",
        "directory_ET_mean_",
        "directory_ET_sum_",
        "directory_fqid_counts",
        "doorblock_ET_max_",
        "doorblock_ET_sum_",
        "doorblock_fqid_counts",
        "elapsed_time_diff_max_",
        "elapsed_time_diff_mean_",
        "gramps_ET_max_",
        "gramps_ET_mean_",
        "groupconvo_ET_mean_",
        "groupconvo_ET_sum_",
        "hover_duration_max_",
        "hover_duration_mean_",
        "intro_ET_max_",
        "intro_ET_mean_",
        "intro_ET_sum_",
        "janitor_ET_max_",
        "map_click_ET_max_",
        "map_click_ET_max_x",
        "map_click_ET_mean_",
        "map_click_ET_mean_x",
        "map_hover_ET_max_",
        "map_hover_ET_mean_",
        "navigate_click_ET_max_",
        "navigate_click_ET_mean_x",
        "navigate_click_event_name_counts",
        "notebook_ET_max_",
        "notebook_ET_mean_",
        "notebook_ET_sum_",
        "notebook_click_ET_max_",
        "notebook_click_ET_max_x",
        "notebook_click_ET_mean_",
        "notebook_click_ET_mean_x",
        "notification_click_ET_max_",
        "notification_click_ET_max_x",
        "notification_click_ET_mean_x",
        "object_click_ET_max_",
        "object_click_ET_max_x",
        "object_click_ET_mean_",
        "object_click_ET_mean_x",
        "object_hover_ET_max_",
        "object_hover_ET_mean_",
        "object_hover_event_name_counts",
        "observation_click_ET_max_",
        "observation_click_ET_max_x",
        "observation_click_ET_mean_",
        "observation_click_ET_mean_x",
        "observation_click_event_name_counts",
        "open_ET_max_",
        "open_ET_mean_",
        "open_name_counts",
        "outtolunch_ET_sum_",
        "outtolunch_fqid_counts",
        "page_max_",
        "page_mean_",
        "person_click_ET_max_x",
        "person_click_ET_mean_",
        "person_click_ET_mean_x",
        "person_click_event_name_counts",
        "photo_ET_max_",
        "photo_ET_sum_",
        "plaque.face.date_ET_max_",
        "plaque.face.date_ET_mean_",
        "plaque.face.date_ET_sum_",
        "plaque.face.date_fqid_counts",
        "plaque_ET_mean_",
        "plaque_fqid_counts",
        "report_ET_max_",
        "report_ET_mean_",
        "report_ET_sum_",
        "report_fqid_counts",
        "retirement_letter_ET_max_",
        "retirement_letter_ET_mean_",
        "retirement_letter_fqid_counts",
        "room_coor_x_max_",
        "room_coor_x_mean_",
        "screen_coor_x_mean_",
        "screen_coor_y_max_",
        "screen_coor_y_mean_",
        "session_number_",
        "teddy_ET_max_",
        "teddy_ET_mean_",
        "teddy_ET_sum_",
        "tobasement_ET_max_",
        "tobasement_ET_mean_",
        "tobasement_ET_sum_",
        "tobasement_fqid_counts",
        "tocloset_ET_mean_",
        "tocollection_ET_mean_",
        "tocollection_ET_sum_",
        "toentry_ET_mean_",
        "toentry_ET_sum_",
        "toentry_fqid_counts",
        "togrampa_ET_max_",
        "tomap_ET_mean_",
        "tomap_ET_sum_",
        "tomap_fqid_counts",
        "tostacks_ET_max_",
        "tostacks_ET_mean_",
        "tostacks_ET_sum_",
        "tunic.capitol_0.hall.chap1_finale_c_text_fqid_counts",
        "tunic.capitol_0.hall_ET_max_",
        "tunic.capitol_0.hall_ET_mean_",
        "tunic.capitol_0.hall_room_fqid_counts",
        "tunic.capitol_0_ET_mean_",
        "tunic.capitol_0_ET_sum_",
        "tunic.historicalsociety.basement.janitor_ET_max_",
        "tunic.historicalsociety.basement.janitor_ET_mean_",
        "tunic.historicalsociety.basement_ET_max_",
        "tunic.historicalsociety.basement_ET_mean_",
        "tunic.historicalsociety.basement_ET_sum_",
        "tunic.historicalsociety.basement_room_fqid_counts",
        "tunic.historicalsociety.closet.doorblock_ET_max_",
        "tunic.historicalsociety.closet.doorblock_ET_mean_",
        "tunic.historicalsociety.closet.gramps.intro_0_cs_0_ET_max_",
        "tunic.historicalsociety.closet.gramps.intro_0_cs_0_ET_mean_",
        "tunic.historicalsociety.closet.gramps.intro_0_cs_0_ET_sum_",
        "tunic.historicalsociety.closet.intro_ET_sum_",
        "tunic.historicalsociety.closet.notebook_ET_mean_",
        "tunic.historicalsociety.closet.retirement_letter.hub_ET_mean_",
        "tunic.historicalsociety.closet.teddy.intro_0_cs_0_ET_max_",
        "tunic.historicalsociety.closet.teddy.intro_0_cs_0_ET_sum_",
        "tunic.historicalsociety.closet.teddy.intro_0_cs_5_ET_max_",
        "tunic.historicalsociety.closet.teddy.intro_0_cs_5_ET_mean_",
        "tunic.historicalsociety.closet_ET_max_",
        "tunic.historicalsociety.closet_ET_mean_",
        "tunic.historicalsociety.closet_ET_sum_",
        "tunic.historicalsociety.closet_room_fqid_counts",
        "tunic.historicalsociety.collection.cs_ET_max_",
        "tunic.historicalsociety.collection.gramps.lost_ET_max_",
        "tunic.historicalsociety.collection.tunic.slip_ET_max_",
        "tunic.historicalsociety.collection.tunic.slip_ET_mean_",
        "tunic.historicalsociety.collection.tunic_ET_mean_",
        "tunic.historicalsociety.collection.tunic_ET_sum_",
        "tunic.historicalsociety.collection_ET_max_",
        "tunic.historicalsociety.collection_room_fqid_counts",
        "tunic.historicalsociety.entry.boss.talktogramps_ET_mean_",
        "tunic.historicalsociety.entry.groupconvo_ET_max_",
        "tunic.historicalsociety.entry.groupconvo_ET_sum_",
        "tunic.historicalsociety.entry_ET_max_",
        "tunic.historicalsociety.entry_room_fqid_counts",
        "tunic.historicalsociety.stacks.outtolunch_ET_mean_",
        "tunic.historicalsociety.stacks_ET_sum_",
        "tunic.historicalsociety_ET_max_",
        "tunic.historicalsociety_ET_mean_",
        "tunic.hub.slip_ET_max_",
        "tunic.hub.slip_ET_mean_",
        "tunic.hub.slip_ET_sum_",
        "tunic.kohlcenter.halloffame.plaque.face.date_ET_max_",
        "tunic.kohlcenter.halloffame.plaque.face.date_ET_sum_",
        "tunic.kohlcenter.halloffame.togrampa_ET_max_",
        "tunic.kohlcenter.halloffame.togrampa_ET_mean_",
        "tunic.kohlcenter.halloffame_ET_max_",
        "tunic.kohlcenter.halloffame_ET_mean_",
        "tunic.kohlcenter.halloffame_ET_sum_",
        "tunic.kohlcenter.halloffame_room_fqid_counts",
        "tunic.kohlcenter_ET_max_",
        "tunic.kohlcenter_ET_mean_",
        "tunic.kohlcenter_ET_sum_",
        "tunic_ET_max_",
        "tunic_ET_mean_",
        "tunic_ET_sum_",
        "tunic_fqid_counts",
        "undefined_ET_max_",
        "undefined_text_ET_sum_",
        "wells_ET_mean_",
        "wells_ET_sum_",
        "wells_fqid_counts",
    },
}
